@hostname = localhost
@port = 5001
@BaseUri = https://{{hostname}}:{{port}}
@contentType = application/json

##############################
# @name register
POST {{BaseUri}}/api/account/register
Content-Type: {{contentType}}

{
    "username":"jim",
    "password":"password"
}


##############################
# @name login
POST {{BaseUri}}/api/account/login
Content-Type: {{contentType}}

{
    "username":"net",
    "password":"password"
}


##############################
# @name getUserWithToken
@authToken = {{login.response.body.$.token}}

GET {{BaseUri}}/api/users/8/
Content-Type: {{contentType}}
Authorization: bearer {{authToken}}